name = "Zeus-Additions"
prefix = "zeus_additions"
mainprefix = "x"

[properties]
author = "johnb43"
url = "https://github.com/johnb432"

[files]
include = [
    "CHANGELOG.md",
    "meta.cpp",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
